### ISSUE TITLE
Integrate molecule and tox

### ISSUE THREAD

**Issue by 0x46616c6b** [systemli/ansible-role-skeleton#1]
- remove vagrant
- integrate molecule and tox with docker

**Comment by xshadow** [comment]
Please review, especially update-role.sh : https://github.com/systemli/ansible-role-skeleton/tree/molecule_tox_docker

**Comment by t2d** [comment]
`update-role.sh` is to destructive. If I already have some tests, it will happily delete them.

**Comment by t2d** [comment]
I added checks to only handle files, that need handling in https://github.com/systemli/ansible-role-skeleton/commit/a6ffdedbea02be6e9ae1e4aea611a3d181a13f06. But of course, we can't update files with those simple means. Would also need some kind of templating.

**Comment by t2d** [comment]
I think, this is solved in current master. Thanks @xshadow for implementing this. However, we should check, how much we still gain compared to using [`molecule init`](http://molecule.readthedocs.io/en/stable-1.24/).
